# Generated by Django 5.2.5 on 2025-09-04 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_useractivity_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='usermodulepermission',
            options={'verbose_name': 'User Module Permission', 'verbose_name_plural': 'User Module Permissions'},
        ),
        migrations.AlterUniqueTogether(
            name='usermodulepermission',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='created_by',
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='attendance_edit',
            field=models.BooleanField(default=False, verbose_name='Attendance Edit'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='attendance_view',
            field=models.BooleanField(default=False, verbose_name='Attendance View'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='classes_edit',
            field=models.BooleanField(default=False, verbose_name='Classes Edit'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='classes_view',
            field=models.BooleanField(default=False, verbose_name='Classes View'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='exams_edit',
            field=models.BooleanField(default=False, verbose_name='Exams Edit'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='exams_view',
            field=models.BooleanField(default=False, verbose_name='Exams View'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='fees_edit',
            field=models.BooleanField(default=False, verbose_name='Fees Edit'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='fees_view',
            field=models.BooleanField(default=False, verbose_name='Fees View'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='payments_edit',
            field=models.BooleanField(default=False, verbose_name='Payments Edit'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='payments_view',
            field=models.BooleanField(default=False, verbose_name='Payments View'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='reports_edit',
            field=models.BooleanField(default=False, verbose_name='Reports Edit'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='reports_view',
            field=models.BooleanField(default=False, verbose_name='Reports View'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='results_edit',
            field=models.BooleanField(default=False, verbose_name='Results Edit'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='results_view',
            field=models.BooleanField(default=False, verbose_name='Results View'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='settings_edit',
            field=models.BooleanField(default=False, verbose_name='Settings Edit'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='settings_view',
            field=models.BooleanField(default=False, verbose_name='Settings View'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='students_edit',
            field=models.BooleanField(default=False, verbose_name='Students Edit'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='students_view',
            field=models.BooleanField(default=False, verbose_name='Students View'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='teachers_edit',
            field=models.BooleanField(default=False, verbose_name='Teachers Edit'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='teachers_view',
            field=models.BooleanField(default=False, verbose_name='Teachers View'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='transport_edit',
            field=models.BooleanField(default=False, verbose_name='Transport Edit'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='transport_view',
            field=models.BooleanField(default=False, verbose_name='Transport View'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='users_edit',
            field=models.BooleanField(default=False, verbose_name='Users Edit'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='users_view',
            field=models.BooleanField(default=False, verbose_name='Users View'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=10),
        ),
        migrations.AlterField(
            model_name='usermodulepermission',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='usermodulepermission',
            table='users_module_permissions',
        ),
        migrations.AddField(
            model_name='customuser',
            name='allowed_modules',
            field=models.ManyToManyField(blank=True, to='users.module'),
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.RemoveField(
            model_name='usermodulepermission',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='usermodulepermission',
            name='can_view',
        ),
        migrations.RemoveField(
            model_name='usermodulepermission',
            name='granted_by',
        ),
        migrations.RemoveField(
            model_name='usermodulepermission',
            name='module',
        ),
    ]
