# Generated by Django 5.2.5 on 2025-09-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='allowed_modules',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
