# Generated by Django 5.2.5 on 2025-09-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_module_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodulepermission',
            name='backup_edit',
            field=models.BooleanField(default=False, verbose_name='Backup Edit'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='backup_view',
            field=models.BooleanField(default=False, verbose_name='Backup View'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='fines_edit',
            field=models.BooleanField(default=False, verbose_name='Fines Edit'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='fines_view',
            field=models.BooleanField(default=False, verbose_name='Fines View'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='messaging_edit',
            field=models.BooleanField(default=False, verbose_name='Messaging Edit'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='messaging_view',
            field=models.BooleanField(default=False, verbose_name='Messaging View'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='promotion_edit',
            field=models.BooleanField(default=False, verbose_name='Promotion Edit'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='promotion_view',
            field=models.BooleanField(default=False, verbose_name='Promotion View'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='school_profile_edit',
            field=models.BooleanField(default=False, verbose_name='School Profile Edit'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='school_profile_view',
            field=models.BooleanField(default=False, verbose_name='School Profile View'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='subjects_edit',
            field=models.BooleanField(default=False, verbose_name='Subjects Edit'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='subjects_view',
            field=models.BooleanField(default=False, verbose_name='Subjects View'),
        ),
    ]
