# Generated by Django 5.0.14 on 2025-08-04 14:57

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admission_number', models.CharField(max_length=20, unique=True, validators=[core.validators.validate_admission_number], verbose_name='Admission Number')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('father_name', models.CharField(max_length=100, verbose_name="Father's Name")),
                ('mother_name', models.CharField(max_length=100, verbose_name="Mother's Name")),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('date_of_admission', models.DateField(verbose_name='Date of Admission')),
                ('aadhaar_number', models.CharField(blank=True, max_length=14, null=True, validators=[core.validators.validate_aadhaar_number])),
                ('pen_number', models.CharField(blank=True, max_length=11, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, verbose_name='Gender')),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Christian', 'Christian'), ('Sikh', 'Sikh'), ('Other', 'Other')], max_length=20, verbose_name='Religion')),
                ('caste_category', models.CharField(choices=[('General', 'General'), ('BC', 'BC'), ('EBC', 'EBC'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('Other', 'Other')], max_length=20, verbose_name='Caste Category')),
                ('address', models.TextField(verbose_name='Address')),
                ('mobile_number', models.CharField(max_length=10, validators=[core.validators.validate_phone_number], verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('blood_group', models.CharField(choices=[('UNKN', 'UNKN'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, verbose_name='Blood Group')),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='students/images/', validators=[core.validators.validate_file_size, core.validators.validate_file_extension])),
                ('aadhar_card', models.FileField(upload_to='students/documents/', validators=[core.validators.validate_file_size, core.validators.validate_file_extension], verbose_name='Aadhar Card')),
                ('transfer_certificate', models.FileField(upload_to='students/documents/', validators=[core.validators.validate_file_size, core.validators.validate_file_extension], verbose_name='Transfer Certificate')),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicclass')),
                ('student_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enrollment_date', models.DateField()),
                ('class_name', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
