# Generated by Django 5.0.14 on 2025-08-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_number'], name='students_st_admissi_321db4_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_class', 'student_section'], name='students_st_student_2ef7c4_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_active', 'created_at'], name='students_st_is_acti_9ef143_idx'),
        ),
    ]
