# Generated by Django 5.0.14 on 2025-09-02 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_students_st_admissi_321db4_idx_and_more'),
        ('subjects', '0006_alter_classsection_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_student_2ef7c4_idx',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_section',
        ),
        migrations.AddField(
            model_name='student',
            name='class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='subjects.classsection'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['class_section'], name='students_st_class_s_7fa89d_idx'),
        ),
    ]
