# Generated by Django 5.2.5 on 2025-09-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_migrate_to_class_section'),
        ('subjects', '0006_alter_classsection_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_is_acti_9ef143_idx',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='is_active',
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['created_at'], name='students_st_created_78a19f_idx'),
        ),
    ]
