# Generated by Django 5.0.14 on 2025-09-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_students_st_is_acti_9ef143_idx_and_more'),
        ('subjects', '0006_alter_classsection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['first_name', 'last_name'], name='students_st_first_n_e9466d_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['mobile_number'], name='students_st_mobile__e128af_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['email'], name='students_st_email_e271bc_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['due_amount'], name='students_st_due_amo_db66c7_idx'),
        ),
    ]
