# Generated by Django 5.0.14 on 2025-09-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_set_default_status'),
        ('students', '0006_alter_student_options_and_more'),
    ]

    operations = [
    ]
