# Generated by Django 5.0.14 on 2025-09-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_merge_20250916_0001'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_status_5e2210_idx',
            old_name='students_st_status_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_status_bc79cd_idx',
            old_name='students_st_status_class_idx',
        ),
    ]
