# Generated by Django 5.2.5 on 2025-09-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicclass',
            options={'ordering': ['name', 'section'], 'verbose_name': 'Class (Legacy)', 'verbose_name_plural': 'Classes (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name'], 'verbose_name': 'Section (Legacy)', 'verbose_name_plural': 'Sections (Legacy)'},
        ),
    ]
