# Generated by Django 5.0.14 on 2025-08-04 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fee_group', models.CharField(choices=[('One Time', 'One Time'), ('Yearly', 'Yearly'), ('Half Yearly', 'Half Yearly'), ('Quarterly', 'Quarterly'), ('Monthly', 'Monthly')], max_length=50)),
                ('group_type', models.CharField(choices=[('Admission Fees', 'Admission Fees'), ('Tuition Fee', 'Tuition Fee'), ('Transport', 'Transport'), ('Exam Fees', 'Exam Fees'), ('Development', 'Development')], max_length=50)),
                ('fee_type', models.CharField(choices=[('Class Based', 'Class Based'), ('Stoppage Based', 'Stoppage Based'), ('General', 'General'), ('Hostel Based', 'Hostel Based')], max_length=50)),
                ('related_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicclass')),
                ('related_stoppage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.stoppage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group_type', models.CharField(max_length=100)),
                ('fee_type', models.CharField(max_length=100)),
                ('amount_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('class_name', models.CharField(blank=True, max_length=50, null=True)),
                ('fee_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_types', to='fees.feesgroup')),
                ('related_stoppage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_feestypes', to='transport.stoppage')),
            ],
            options={
                'unique_together': {('fee_group', 'group_type', 'fee_type', 'amount_type', 'class_name', 'related_stoppage')},
            },
        ),
    ]
