# Generated by Django 5.2.5 on 2025-09-07 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_migrate_to_class_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feesgroup',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='feestype',
            name='is_active',
        ),
    ]
