# Generated by Django 5.0.14 on 2025-09-09 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_fix_fees_consistency'),
        ('fees', '0003_remove_feesgroup_is_active_remove_feestype_is_active'),
    ]

    operations = [
    ]
