# Generated by Django 5.0.14 on 2025-09-10 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_recreate_feestype'),
        ('fees', '0004_merge_20250910_0426'),
    ]

    operations = [
    ]
