# Generated by Django 5.2.5 on 2025-09-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_dynamic_fee_structure'),
        ('fees', '0005_merge_0003_recreate_feestype_0004_merge_20250910_0426'),
    ]

    operations = [
    ]
