# Generated by Django 5.2.5 on 2025-09-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_fix_amount_type_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestype',
            name='amount_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feestype',
            name='class_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
