# Generated by Django 5.0.14 on 2025-08-04 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
        ('fines', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fine',
            name='fees_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.feesgroup'),
        ),
        migrations.AddField(
            model_name='fine',
            name='fees_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.feestype'),
        ),
        migrations.AddField(
            model_name='fine',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='students.student'),
        ),
        migrations.AddField(
            model_name='feedepositfine',
            name='fine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fines.fine'),
        ),
        migrations.AddField(
            model_name='fineauditlog',
            name='fine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='fines.fine'),
        ),
        migrations.AddField(
            model_name='fineauditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finestudent',
            name='fine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fine_students', to='fines.fine'),
        ),
        migrations.AddField(
            model_name='finestudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='finetemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finetemplate',
            name='fees_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.feesgroup'),
        ),
        migrations.AddField(
            model_name='finetemplate',
            name='fees_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.feestype'),
        ),
        migrations.AddField(
            model_name='finetemplate',
            name='fine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fines.finetype'),
        ),
        migrations.AddField(
            model_name='fine',
            name='fine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fines.finetype'),
        ),
        migrations.AddField(
            model_name='finewaiver',
            name='fine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='fines.fine'),
        ),
        migrations.AddField(
            model_name='finewaiver',
            name='target_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='finewaiver',
            name='waived_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='finestudent',
            index=models.Index(fields=['fine', 'student'], name='fines_fines_fine_id_bd84f9_idx'),
        ),
        migrations.AddIndex(
            model_name='finestudent',
            index=models.Index(fields=['is_paid'], name='fines_fines_is_paid_e5a3bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='finestudent',
            unique_together={('fine', 'student')},
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['target_scope'], name='fines_fine_target__75ae7e_idx'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['class_group'], name='fines_fine_class_g_59d438_idx'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['student'], name='fines_fine_student_ecdcda_idx'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['applied_date'], name='fines_fine_applied_b1f696_idx'),
        ),
    ]
