# Generated by Django 5.0.14 on 2025-08-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedepositfine',
            name='fee_deposit',
        ),
        migrations.RemoveField(
            model_name='feedepositfine',
            name='fine',
        ),
        migrations.RemoveField(
            model_name='feedepositfine',
            name='target_student',
        ),
        migrations.RemoveField(
            model_name='finewaiver',
            name='fine',
        ),
        migrations.RemoveField(
            model_name='finewaiver',
            name='target_student',
        ),
        migrations.RemoveField(
            model_name='finewaiver',
            name='waived_by',
        ),
        migrations.RemoveIndex(
            model_name='fine',
            name='fines_fine_student_ecdcda_idx',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='delay_days',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='edited_history',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='fees_group',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='last_edited',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='payment_transaction_id',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='student',
        ),
        migrations.DeleteModel(
            name='FeeDepositFine',
        ),
        migrations.DeleteModel(
            name='FineWaiver',
        ),
    ]
