# Generated by Django 5.2.5 on 2025-09-02 14:41

from django.db import migrations, connection

def safe_remove_index(apps, schema_editor):
    """Safely remove index if it exists"""
    with connection.cursor() as cursor:
        # Check if index exists before trying to remove it
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='index' AND name='fines_fine_class_g_59d438_idx'
        """)
        if cursor.fetchone():
            cursor.execute("DROP INDEX fines_fine_class_g_59d438_idx")

def reverse_safe_remove_index(apps, schema_editor):
    """Reverse operation - recreate index if needed"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0004_migrate_to_class_section'),
    ]

    operations = [
        migrations.RunPython(safe_remove_index, reverse_safe_remove_index),
    ]