# Generated by Django 5.0.14 on 2025-09-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0006_final_index_cleanup'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fine',
            name='fines_fine_class_g_59d438_idx',
        ),
        migrations.RenameIndex(
            model_name='fine',
            new_name='fines_fine_class_s_0515ff_idx',
            old_fields=('class_section',),
        ),
        migrations.AlterIndexTogether(
            name='fine',
            index_together=set(),
        ),
    ]
