# Generated by Django 5.2.5 on 2025-09-07 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0007_remove_fine_fines_fine_class_g_59d438_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fine',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='fineauditlog',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='finestudent',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='finetemplate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='finetype',
            name='is_active',
        ),
    ]
