# Generated by Django 5.0.14 on 2025-08-04 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_no', models.CharField(max_length=50)),
                ('deposit_date', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Cheque', 'Cheque'), ('UPI', 'UPI'), ('Card', 'Card')], default='Cash', max_length=20)),
                ('transaction_no', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_source', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('fees_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.feesgroup')),
                ('fees_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.feestype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_deposits', to='students.student')),
            ],
            options={
                'verbose_name': 'Fee Deposit',
                'verbose_name_plural': 'Fee Deposits',
                'ordering': ['-deposit_date'],
            },
        ),
    ]
