# Generated by Django 5.0.14 on 2025-09-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_fees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedeposit',
            name='fees_group',
        ),
        migrations.RemoveField(
            model_name='feedeposit',
            name='fees_type',
        ),
        migrations.AlterField(
            model_name='feedeposit',
            name='payment_mode',
            field=models.CharField(default='Cash', max_length=20),
        ),
    ]
