# Generated by Django 5.0.14 on 2025-09-09 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0003_remove_feesgroup_is_active_remove_feestype_is_active'),
        ('fines', '0008_remove_fine_is_active_remove_fineauditlog_is_active_and_more'),
        ('student_fees', '0002_remove_feedeposit_fees_group_and_more'),
        ('students', '0006_alter_student_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('auto_generated', models.BooleanField(default=False)),
                ('fine_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fines.finetemplate')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_fines', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('academic_year', models.CharField(default='2024-25', max_length=20)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feestype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_fees', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allocation_date', models.DateTimeField(auto_now_add=True)),
                ('applied_fine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fee_management.appliedfine')),
                ('fee_deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='student_fees.feedeposit')),
                ('student_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fee_management.studentfee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='appliedfine',
            index=models.Index(fields=['student', 'is_paid'], name='fee_managem_student_311dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedfine',
            index=models.Index(fields=['applied_date'], name='fee_managem_applied_789d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['student', 'is_paid'], name='fee_managem_student_c485f5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['due_date'], name='fee_managem_due_dat_18ec9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentfee',
            unique_together={('student', 'fee_type', 'academic_year')},
        ),
    ]
