# Generated by Django 5.0.14 on 2025-08-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_name', models.CharField(default='School Admin', max_length=100)),
                ('sender_phone', models.CharField(help_text='Phone number used as sender for SMS and WhatsApp', max_length=15)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Messaging Configuration',
                'verbose_name_plural': 'Messaging Configurations',
            },
        ),
    ]
