# Generated by Django 5.2.5 on 2025-08-30 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0003_remove_feedepositfine_fee_deposit_and_more'),
        ('messaging', '0003_whatsappgroup_groupmessage'),
        ('student_fees', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_sms_provider', models.CharField(choices=[('twilio', 'Twilio'), ('messagecentral', 'MessageCentral')], default='messagecentral', max_length=20)),
                ('default_whatsapp_provider', models.CharField(choices=[('twilio', 'Twilio'), ('messagecentral', 'MessageCentral')], default='messagecentral', max_length=20)),
                ('enable_fee_notifications', models.BooleanField(default=True)),
                ('enable_fine_notifications', models.BooleanField(default=True)),
                ('enable_provider_fallback', models.BooleanField(default=True)),
                ('admin_notification_numbers', models.TextField(blank=True, help_text='Comma-separated list of admin mobile numbers')),
            ],
            options={
                'verbose_name': 'Messaging Settings',
                'verbose_name_plural': 'Messaging Settings',
            },
        ),
        migrations.AddField(
            model_name='messagelog',
            name='fee_deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_fees.feedeposit'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='fine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fines.fine'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='provider',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='message_type',
            field=models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('custom', 'Custom Message'), ('fee_deposit_parent', 'Fee Deposit - Parent'), ('fee_deposit_admin', 'Fee Deposit - Admin'), ('fine_creation_parent', 'Fine Creation - Parent'), ('fine_application_admin', 'Fine Application - Admin')], max_length=30),
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message_type', models.CharField(max_length=30)),
                ('template_content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
