# Generated by Django 5.2.5 on 2025-08-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_messagingsettings_messagelog_fee_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagingconfig',
            name='messagecentral_customer_id',
            field=models.CharField(blank=True, help_text='Message Central Customer ID', max_length=100),
        ),
        migrations.AddField(
            model_name='messagingconfig',
            name='messagecentral_email',
            field=models.EmailField(blank=True, help_text='Message Central Account Email', max_length=254),
        ),
        migrations.AddField(
            model_name='messagingconfig',
            name='messagecentral_password',
            field=models.CharField(blank=True, help_text='Message Central Password', max_length=100),
        ),
        migrations.AddField(
            model_name='messagingconfig',
            name='messagecentral_sender_id',
            field=models.CharField(blank=True, help_text='Message Central Sender ID', max_length=10),
        ),
        migrations.AddField(
            model_name='messagingconfig',
            name='twilio_account_sid',
            field=models.CharField(blank=True, help_text='Twilio Account SID', max_length=100),
        ),
        migrations.AddField(
            model_name='messagingconfig',
            name='twilio_auth_token',
            field=models.CharField(blank=True, help_text='Twilio Auth Token', max_length=100),
        ),
        migrations.AddField(
            model_name='messagingconfig',
            name='twilio_phone_number',
            field=models.CharField(blank=True, help_text='Twilio Phone Number (with country code)', max_length=20),
        ),
        migrations.AddField(
            model_name='messagingconfig',
            name='whatsapp_access_token',
            field=models.CharField(blank=True, help_text='WhatsApp Access Token', max_length=500),
        ),
        migrations.AddField(
            model_name='messagingconfig',
            name='whatsapp_business_account_id',
            field=models.CharField(blank=True, help_text='WhatsApp Business Account ID', max_length=100),
        ),
        migrations.AddField(
            model_name='messagingconfig',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, help_text='WhatsApp Phone Number ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='messagingsettings',
            name='default_sms_provider',
            field=models.CharField(choices=[('twilio', 'Twilio')], default='twilio', max_length=20),
        ),
        migrations.AlterField(
            model_name='messagingsettings',
            name='default_whatsapp_provider',
            field=models.CharField(choices=[('twilio', 'Twilio')], default='twilio', max_length=20),
        ),
    ]
