# Generated by Django 5.2.5 on 2025-08-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_messagingconfig_messagelog_class_filter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappgroup',
            name='class_filter',
        ),
        migrations.RemoveField(
            model_name='whatsappgroup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='messagingconfig',
            name='messagecentral_customer_id',
        ),
        migrations.RemoveField(
            model_name='messagingconfig',
            name='messagecentral_email',
        ),
        migrations.RemoveField(
            model_name='messagingconfig',
            name='messagecentral_password',
        ),
        migrations.RemoveField(
            model_name='messagingconfig',
            name='messagecentral_sender_id',
        ),
        migrations.RemoveField(
            model_name='messagingconfig',
            name='twilio_account_sid',
        ),
        migrations.RemoveField(
            model_name='messagingconfig',
            name='twilio_auth_token',
        ),
        migrations.RemoveField(
            model_name='messagingconfig',
            name='twilio_phone_number',
        ),
        migrations.RemoveField(
            model_name='messagingconfig',
            name='whatsapp_access_token',
        ),
        migrations.RemoveField(
            model_name='messagingconfig',
            name='whatsapp_business_account_id',
        ),
        migrations.RemoveField(
            model_name='messagingconfig',
            name='whatsapp_enabled',
        ),
        migrations.RemoveField(
            model_name='messagingconfig',
            name='whatsapp_phone_number_id',
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='message_type',
            field=models.CharField(choices=[('SMS', 'SMS')], default='SMS', max_length=10),
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
        migrations.DeleteModel(
            name='WhatsAppGroup',
        ),
    ]
