# Generated by Django 5.2.5 on 2025-09-07 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_migrate_to_class_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagelog',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='messagerecipient',
            name='is_active',
        ),
    ]
