# Generated by Django 5.2.5 on 2025-09-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_remove_messagelog_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='source_module',
            field=models.CharField(choices=[('messaging', 'Messaging'), ('student_fees', 'Student Fees'), ('reports', 'Reports'), ('attendance', 'Attendance'), ('transport', 'Transport'), ('fines', 'Fines'), ('system', 'System')], default='messaging', max_length=20),
        ),
    ]
