# Generated by Django 5.2.5 on 2025-09-02 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_academicclass_options_alter_section_options'),
        ('promotion', '0001_initial'),
        ('subjects', '0006_alter_classsection_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promotionrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='current_class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_from', to='subjects.classsection'),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='next_class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_to', to='subjects.classsection'),
        ),
        migrations.AlterField(
            model_name='promotionrule',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_from_legacy', to='core.academicclass'),
        ),
        migrations.AlterField(
            model_name='promotionrule',
            name='next_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_to_legacy', to='core.academicclass'),
        ),
    ]
