# Generated by Django 5.2.5 on 2025-09-07 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_cleanup_promotion_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionrule',
            name='is_active',
        ),
    ]
