# Generated by Django 5.0.14 on 2025-09-09 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0005_remove_promotionrule_is_active'),
        ('students', '0005_remove_student_students_st_is_acti_9ef143_idx_and_more'),
        ('subjects', '0006_alter_classsection_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promotionrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='academic_year',
            field=models.CharField(default='2024-25', max_length=10),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='from_class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_from', to='subjects.classsection'),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='minimum_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='to_class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_to', to='subjects.classsection'),
        ),
        migrations.AlterField(
            model_name='promotionrule',
            name='current_class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_promotion_from', to='subjects.classsection'),
        ),
        migrations.AlterField(
            model_name='promotionrule',
            name='min_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotionrule',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotionrule',
            name='next_class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_promotion_to', to='subjects.classsection'),
        ),
        migrations.AlterUniqueTogether(
            name='promotionrule',
            unique_together={('from_class_section', 'to_class_section', 'academic_year')},
        ),
        migrations.CreateModel(
            name='StudentPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(default='2024-25', max_length=10)),
                ('promotion_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('from_class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_promotions_from', to='subjects.classsection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='students.student')),
                ('to_class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_promotions_to', to='subjects.classsection')),
            ],
            options={
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
