# Generated by Django 5.0.14 on 2025-08-18 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('section_name', models.CharField(max_length=10)),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['class_name', 'section_name'],
                'unique_together': {('class_name', 'section_name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='subjectassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.classsection'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectassignment',
            unique_together={('class_section', 'subject')},
        ),
        migrations.RemoveField(
            model_name='subjectassignment',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='subjectassignment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subjectassignment',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='subjectassignment',
            name='updated_at',
        ),
    ]
