# Generated by Django 5.0.14 on 2025-08-18 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_class_section_remove_subject_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectassignment',
            name='class_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subjects.classsection'),
            preserve_default=False,
        ),
    ]
