# Generated by Django 5.0.14 on 2025-09-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_subjectassignment_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classsection',
            options={},
        ),
    ]
