# Generated by Django 5.2.5 on 2025-09-27 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=32, unique=True)),
                ('demo_started', models.DateTimeField(auto_now_add=True)),
                ('demo_expires', models.DateTimeField()),
                ('is_licensed', models.BooleanField(default=False)),
                ('license_key', models.CharField(blank=True, max_length=17, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demo Status',
                'verbose_name_plural': 'Demo Statuses',
            },
        ),
        migrations.CreateModel(
            name='LicenseActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key_attempted', models.CharField(max_length=17)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('attempted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('demo_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.demostatus')),
            ],
            options={
                'verbose_name': 'License Activation',
                'verbose_name_plural': 'License Activations',
            },
        ),
    ]
