# Generated by Django 5.0.14 on 2025-08-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=16)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=16, null=True)),
                ('checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('schema_version', models.CharField(blank=True, max_length=32, null=True)),
                ('report_json', models.JSONField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'backup_jobs',
                'indexes': [models.Index(fields=['created_at'], name='backup_jobs_created_932e00_idx'), models.Index(fields=['status'], name='backup_jobs_status_a40201_idx')],
            },
        ),
        migrations.CreateModel(
            name='RestoreJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=16)),
                ('source_type', models.CharField(choices=[('backup', 'backup'), ('uploaded', 'uploaded')], default='backup', max_length=16)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=16, null=True)),
                ('mode', models.CharField(choices=[('replace', 'replace'), ('merge', 'merge')], default='merge', max_length=16)),
                ('duplicate_strategy', models.CharField(choices=[('skip', 'skip'), ('update', 'update')], default='update', max_length=16)),
                ('schema_version', models.CharField(blank=True, max_length=32, null=True)),
                ('validation_result_json', models.JSONField(blank=True, null=True)),
                ('report_json', models.JSONField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'restore_jobs',
                'indexes': [models.Index(fields=['created_at'], name='restore_job_created_1966e2_idx'), models.Index(fields=['status'], name='restore_job_status_c0686d_idx')],
            },
        ),
    ]
